### ISSUE TITLE
Bug: Or (||) filter expressions not working properly

### ISSUE THREAD

**Issue by akashlevy** [The-OpenROAD-Project/OpenSTA#217]
I'm looking for reset ports in `picorv32` design synthesized on `sky130hd`. There is one reset port called `resetn`. However, I get different results for the following two commands:
```
% get_ports -filter ((name=~rst*)||(name=~reset*)) *
% get_ports -filter ((name=~reset*)||(name=~rst*)) *
_6042a024dd7f0000_p_Port
```
These commands should obviously give the same results, since OR (||) is a commutative operation.

Using latest version of OpenSTA 2.4.0. Happy to provide test files to reproduce if needed.

**Comment by jjcherry56** [comment]
If you had spaces around the || as the documentation indicates it would have worked.
I fixed it to not require the spaces (which means the filter has to be in quotes) in 
https://github.com/parallaxsw/OpenSTA.git commit
4146e623 get_* -filter do not require spaces around ||/&&

But since the whole point of get_ports is to pattern match the port names there isn't much point in using -filter arg.

[concat [get_ports rst*] [get_ports reset*]]

**Comment by akashlevy** [comment]
Thanks James, this is helpful
