### ISSUE TITLE
Couldn't able to read SPEF in openSTA

### ISSUE THREAD

**Issue by Tanvir-Rizve** [The-OpenROAD-Project/OpenSTA#245]
I encountered an issue while trying to read a Standard Parasitic Exchange Format (SPEF) file using OpenSTA. The error occurs at the line where a port has a negative index. Specifically, the SPEF file contains a port with the naming convention port_a[-2]. 
![image (1)](https://github.com/user-attachments/assets/89460ae8-6ff0-412a-aed2-6fbbe056ef3f)
![image (2)](https://github.com/user-attachments/assets/b2d0121c-f3fb-465c-8330-b11408684a5f)

While OpenSTA processes ports with positive indices, such as port_a[2], without any issues, it fails when encountering ports with negative indices.

![image (4)](https://github.com/user-attachments/assets/83902386-3387-4854-97e1-ade43d580564)
![image (5)](https://github.com/user-attachments/assets/762d0c15-dbeb-4769-9b71-5756ba073a5e)

**Comment by rovinski** [comment]
As far as I can tell from the SPEF spec, that's not a valid `bit_identifier` because it must be a positive integer.
![image](https://github.com/user-attachments/assets/9f4f40f1-a30b-4006-acfa-d9d4e2a06da1)
In the best case, you would have to escape `[`, `-`, and `]` using `\` which would no longer treat it as a bus. Or make sure all bus indices are positive.

**Comment by maliberty** [comment]
Issues or PRs should be filed with https://github.com/parallaxsw/OpenSTA if still relevant.  This is effectively a fork (though not strictly for historical reasons).
