### ISSUE TITLE
Replacement for '-x' argument

### ISSUE THREAD

**Issue by byzantic** [The-OpenROAD-Project/OpenSTA#27]
Sigh - I found the -x command line argument quite useful. I used to use it to construct an sta call from variables in my make file.

Now I have to first of all create a command script, and then invoke sta with that script (not forgetting -exit of course .. as if I would ..)

In my dreams, I would have a '-x' argument that worked multiple times, so that I could do something like

sta -exit > report-file \\
 -x "read_liberty -max ${SYNTH.EARLY.LIB}" \\
 -x "read_liberty -min ${SYNTH.LATE.LIB}"    \\
 -x "read_verilog      ${VLOG.GATE.NET}"      \\
 -x "link_design       ${VLOG.GATE.TOP}"       \\
 -x "report_checks"

.. where SYNTH.EARLY.LIB is a make variable, set elsewhere. Yosys has an argument like this, the -p option.

Of course, I can survive without this using a script generation technique, so it's not a showstopper.

**Comment by jjcherry56** [comment]
Since you seem to understand redirection for output maybe you should try it
for input.
Note that ";" separates tcl commands.  You can make your dreams come true
trivially:

echo "read_liberty -max ${SYNTH.EARLY.LIB}; read_liberty -min
${SYNTH.LATE.LIB}"; read_verilog ${VLOG.GATE.NET <http://vlog.gate.net/>}";
link_design ${VLOG.GATE.TOP};report_checks" | sta > report_file

I detected evidence of brain damaged liberty files missing one of hold or
setup checks based on IBM standards unfortunately propagated by tau contest
examples. Make sure your early/late libraries have both setup and hold
checks in them per S company protocol.
